import Hero from "./components/Hero/Hero"
import OurServices from "./components/OurServices/OurServices"

export const metadata = {
  title: 'Home | Paragon Design',
  description: 'Generated by create Paragon Design',
}

export default function Home() {
  return (
    <main>
      <Hero />
      <OurServices />
    </main>
  )
}
