import Hero from "./components/Hero/Hero"
import OurProjects from "./components/OurProjects/OurProjects"
import OurServices from "./components/OurServices/OurServices"
import OurBlogs from "./components/OurBlogs/OurBlogs";

export const metadata = {
  title: 'Home | Paragon Design',
  description: 'Generated by create Paragon Design',
}

export default function Home() {
  return (
    <main>
      <Hero />
      <OurServices />
      <OurProjects />
      <OurBlogs />
    </main>
  )
}
