
export const metadata = {
  title: 'Home | Paragon Design',
  description: 'Generated by create Paragon Design',
}

export default function Home() {
  return (
    <main>
      <h1>Home</h1>
    </main>
  )
}
